name: "Diala Passil"
type : "Haunted Exile"
tier: "hero"
health : 12
endurance : 5
speed : 4
defense_dice : 
  - "white"
strength : 
  - "blue"
  - "green"
insight : 
  - "blue"
  - "green"
  - "yellow"
tech : 
  - "blue"
abilities :
  - text : "Precise Strike"
    cost: 
      - "strain"
      - "strain"
      - "melee"
      - "activation"
    reward :
      - "remove"
      - "defense_dice"
  - text: "Foresight"
    cost: 
      - "strain"
    reward:
      - "reroll"
      - "defense_dice"
    
